In [3]:
from scipy import linalg
import numpy as np

# Initialize M
M = np.array([[1, 2], [2, 1], [3, 4], [4, 3]])
print("The matrix M :\n", M)

U_mat, s_mat, Vh_mat = linalg.svd(M, full_matrices = False)

print("U :\n", U_mat)
print("Singular matrix :\n", s_mat)
print("V transpose :\n", Vh_mat)

M_transpose = M.T
print("M_transpose * M = \n", np.matmul(M_transpose, M))
w, v = linalg.eigh(np.matmul(M_transpose, M))
idx = np.argsort(-w)
w = w[idx]
v = v[:,idx]
print("Evals :\n", w)
print("Evecs :\n", v)

The matrix M :
 [[1 2]
 [2 1]
 [3 4]
 [4 3]]
U :
 [[-0.27854301  0.5       ]
 [-0.27854301 -0.5       ]
 [-0.64993368  0.5       ]
 [-0.64993368 -0.5       ]]
Singular matrix :
 [7.61577311 1.41421356]
V transpose :
 [[-0.70710678 -0.70710678]
 [-0.70710678  0.70710678]]
M_transpose * M = 
 [[30 28]
 [28 30]]
Evals :
 [58.  2.]
Evecs :
 [[ 0.70710678 -0.70710678]
 [ 0.70710678  0.70710678]]
